### ISSUE TITLE
BUG - Merged Lead and Lead IDs seem to be switched

### ISSUE THREAD

**Issue by khedgecock** [fivetran/dbt_marketo#17]
**Are you a current Fivetran customer?** 
Kristin Hedgecock, Analytics Manager, Company Cam

**Describe the bug**
In STG_MARKETO__ACTIVITY_MERGE_LEADS the code is attempting to case/convert a field with multiple IDs to a numeric field. This leads to a failure because multiple lead ids are merged into a single id. 

stg_marketo__lead is failing b/c of the records that have multiple copies `,` in the merged field. 

![image](https://user-images.githubusercontent.com/92458478/148828924-a42cf33e-c556-47c8-aa3b-477bb46c0a16.png)

**Steps to reproduce**

**Expected behavior**
It not to fail 😊  

**Project variables configuration**

```yml
copy dbt_project.yml here
```

**Package Version**

```yml
copy packages.yml here
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 
Mid Critical

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-jamie** [comment]
hi @khedgecock - I've made  the code fix if you could test it out! 
```yml
# packages.yml
packages:
  - git: https://github.com/fivetran/dbt_marketo.git
    revision: bug/switch-merge-lead-ids
```

the code change itself is actually just in the `dbt_marketo_source` package, but i added this working branch to the transform package to ensure that we're not introducing any downstream funkiness

**Comment by khedgecock** [comment]
Silly question - what's the best steps to pull down this version and test it out?

**Comment by fivetran-jamie** [comment]
ah definitely not silly! you'd add this code

```yml
# packages.yml
packages:
  - git: https://github.com/fivetran/dbt_marketo.git
    revision: bug/switch-merge-lead-ids
```
to your project's `packages.yml` file (and remove or comment out the dbt-hub syntax for installing the package, which probably looks like the following)
```yml
packages:
  - package: fivetran/marketo
    version: [">=0.6.0", "<0.7.0"]
```

and execute a `dbt run` to ensure that the errors are all gone
